### ISSUE TITLE
Test cases does not return a verdict

### ISSUE THREAD

**Issue by vasilischatziathanasiou** [AuthEceSoftEng/web-recorder-server#7]
There seems to be an issue with the server, since test case does not return any verdict (remains forever in status "running"). Moreover, test cases that were running a couple of days ago like for example a simple login, now fail with Error: ELEMENT CANNOT BE ASSIGNED.

**Comment by dimitrisniras** [comment]
Hi @vasilischatziathanasiou ,

This is a host issue due to lack of computing resources. We are going to move the app to another host.
